[package]
name = "comet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
bitfield-struct = "0.6.0"
bitflags = "2.4.2"
clap = { version = "4.5.1", features = ["derive"] }
sa = "2.0.0"
thiserror = "1.0.57"
