use_small_heuristics = "Default"
enum_discrim_align_threshold = 16
struct_field_align_threshold = 16
fn_params_layout = "Compressed"

brace_style ="PreferSameLine"
fn_single_line = true
max_width = 150